const batch1 = [
  { name: 'Acio, Angelika S.' },
  { name: 'Adolacion, Jesmar Troy A.' },
  { name: 'Aguacito, Rey Lloyd G.' },
  { name: 'Baban, Joshua A.' },
  { name: 'Barcelo, Frances Joy U.' },
  { name: 'Cabalfin, Herlyn Grace C.' },
  { name: 'Cabañas, Lovely C.' },
  { name: 'Cañonero, Mark Gerard S.' },
  { name: 'Capeñanes, Jamela C.' },
  { name: 'Castor, Kayla Millen G.' },
  { name: 'Chavez, Almira Grace C.' },
  { name: 'Copio, Yennah Mae G.' },
  { name: 'Daria, Mary Jarnellen V.' },
  { name: 'Dela Cruz, John Guiller P.' },
  { name: 'Fullon, Krystyv Maren S.' },
  { name: 'Gicanal, Flora May D.' },
  { name: 'Gonzaga, Kyla Mae B.' },
  { name: 'Jinon, Jon Robien E.' },
  { name: 'Lancara, Vincent T.' },
  { name: 'Lavente, Mark Ryan D.' },
  { name: 'Leagogo, Nezel C.' },
  { name: 'Libeta, Mikaela Andrea A.' },
  { name: 'Pintor, Lorejoy M.' },
  { name: 'Solanib, Prince Deo S.' },
  { name: 'Soldevilla, Francis Rey M.' },
  { name: 'Sollano, Neal Chris S.' },
  { name: 'Solvero, Juisa Grace R.' },
  { name: 'Sustento, Kimberly Joyce B.' },
  { name: 'Suyao, Cloei Antonette P.' },
  { name: 'Tangub, Vijay' },
  { name: 'Tunggak, Marianne Therese E.' },
  { name: 'Vilchez, Gilmore M.' },
  { name: 'Abulencia, Paolo Jose  G.' },
  { name: 'Angulo, Fritz Bryan N.' },
  { name: 'Barba, Horacio Jason A.' },
  { name: 'Bayot, Allaikha P.' },
  { name: 'Cabalonga, Kezia Mari C.' },
  { name: 'Cadaguman, Louie Steven L.' },
  { name: 'Caliuag, Marikarr S.' },
  { name: 'Cariño, Nouriel John C.' },
  { name: 'Castrojas, Kristine Louise, C.' },
  { name: 'Ciasico, Ma. Sheenamae P.' },
  { name: 'Diosaban, Timothy A.' },
]

const batch2 = [
  { name: 'Evangelista, Jeniusfem Richie A.' },
  { name: 'Galvez, Mike Jan C.' },
  { name: 'Gortayo, Jay Mar E.' },
  { name: 'Guzman, Lyd Ryan A.' },
  { name: 'Hofileña, Leander T.' },
  { name: 'Lavilla, Sophia Rea O.' },
  { name: 'Lebrilla, Danica Marie A.' },
  { name: 'Linganay, Marissa Grace M.' },
  { name: 'Molina, Janley R.' },
  { name: 'Rabe, Jett Adriel M.' },
  { name: 'Rebaya, Clarence Keith S.' },
  { name: 'Resurriaga, Justin Emman M.' },
  { name: 'Rodriguez, John Christian V.' },
  { name: 'Sanchez, Trixia Starr D.' },
  { name: 'Sapan, GV D.' },
  { name: 'Sevilla, Winston C.' },
  { name: 'Tampe, Mayfen E.' },
  { name: 'Trance, Raymond Ladgie G.' },
  { name: 'Vecino, Jenemie U.' },
  { name: 'Wong Josi Mari C.' },
  { name: 'Abancio, Kia Sherrice P.' },
  { name: 'Almodiel, Kristine Mae G.' },
  { name: 'Amio, Ayrra Jane R.' },
  { name: 'Armada, Jason Frederick A.' },
  { name: 'Barredo, Christine Anne D.' },
  { name: 'Barrieta, Branwe Allan M.' },
  { name: 'Basco, Elme Joy H.' },
  { name: 'Chavez, Hugo Leroy D.' },
  { name: 'Deles, Christine M.' },
  { name: 'Fuentes, Kenneth G.' },
  { name: 'Gange, Ein Dominic B.' },
  { name: 'Gappe, Francis Mathew M.' },
  { name: 'Garcia, Veronica Rose G.' },
  { name: 'Gegrimal, Denise Marie T.' },
  { name: 'Gumban, Paul Ian M.' },
  { name: 'Honeyman, John A.' },
  { name: 'Isiderio, Nicole Grace C.' },
  { name: 'Jandongan, Elian G.' },
  { name: 'Luis, Lennox G.' },
  { name: 'Magoliman, Vincent L.' },
  { name: 'Maravilloso, Mark Ian T.' },
  { name: 'Masangcay, Faith Angel M.' },
]

const batch3 = [
  { name: 'Millares, Francine Anne N.' },
  { name: 'Mioten, Ma. Hyacinth E.' },
  { name: 'Moises, Ella Marie G.' },
  { name: 'Napatal, Karl Matthew C.' },
  { name: 'Ogalinola, Lovelie P.' },
  { name: 'Reyes, Carlo Adrian R.' },
  { name: 'Rubido, Samuel Cezar Jr. N.' },
  { name: 'Sarabia, Christian T.' },
  { name: 'Servidad, Jomel N.' },
  { name: 'Sevillena, Camille Aryne S.' },
  { name: 'Soberano, Jay Czhelle B.' },
  { name: 'Subong, Mark Vincent D.' },
  { name: 'Sustiguer, Neil Ryan S.' },
  { name: 'Tabaque, Aris Ernst ' },
  { name: 'Tezara, Thor Felart nL.' },
  { name: 'Tolato, Jesmar O.' },
  { name: 'Alarba, Justin Kent L.' },
  { name: 'Andres, Marjorie A.' },
  { name: 'Cabida, Kristian Allan I.' },
  { name: 'Cabusbusan, Jean Kyle G.' },
  { name: 'Calamro, Zyriel Jay F.' },
  { name: 'Celeste, Rapcel P.' },
  { name: 'Cinco, Arianne Nicole A.' },
  { name: 'Consular, Hazel June A.' },
  { name: 'Cordero, Rica L.' },
  { name: 'Darle, Clarice Jane P.' },
  { name: 'De Leon, Rover Gil C.' },
  { name: 'Distor, Janne Christian A.' },
  { name: 'Duran, Joseph Anthony M.' },
  { name: 'Elizarde, Jeancel H.' },
  { name: 'Elloran, Jessa Mae E.' },
  { name: 'Escosar, Richard David M.' },
  { name: 'Fasciol, Ronil Amos T.' },
  { name: 'Gallego, Angel G.' },
  { name: 'Gentica, Andrei Ammanuel' },
  { name: 'Gonzaga, Roel John P.' },
  { name: 'Inawasan, Rouen I.' },
  { name: 'Labrague, Aphrodite E.' },
  { name: 'Luciano, Kristen Ann Joy F.' },
  { name: 'Macahilo, Amiel John B.' },
  { name: 'Mendoza, Kristara C.' },
  { name: 'Nallas, Gabriel Jess J.' },
  { name: 'Odrada, Rafael Louis H.' },
]

const batch4 = [
  { name: 'Opanto, Mark Junel O.' },
  { name: 'Penetrante, Joeleen Jay C.' },
  { name: 'Perez, Inceasa Bliss B.' },
  { name: 'Pollicar, Edelen Aleja E.' },
  { name: 'Redondo, Shenly Jazreel F.' },
  { name: 'Rubinos, Christopher Joseph T.' },
  { name: 'Rubite, Jann Florence O.' },
  { name: 'Salcedo, Audrey B.' },
  { name: 'Sapitanan, Gian Angelo S.' },
  { name: 'Segovia, Osbert Peter A.' },
  { name: 'Soncio, Paul Adrian D.' },
  { name: 'Torres, Joseph Robert T.' },
  { name: 'Villar, Kyle Zandre A.' },
  { name: 'Zaldarriaga, Jezreel E.' },
  { name: 'Abesamis, Bryan Kent S.' },
  { name: 'Arceta, Kaixen Gail J.' },
  { name: 'Atiga, Jade B.' },
  { name: 'Belarmino, Nathaniel L.' },
  { name: 'Bersonia, Marie Rose A.' },
  { name: 'Castañeda, Jayvee B.' },
  { name: 'Castro, MC Kelly D.' },
  { name: 'Demontaño, Kent Christian L.' },
  { name: 'Doting, Shiena Mae B.' },
  { name: 'Espares, Gene Darwin P.' },
  { name: 'Gange, Joshua Ryan S.' },
  { name: 'Gardose, Nervin G.' },
  { name: 'Genovate, Paul Anthony F.' },
  { name: 'Herrera, Hans Christian F.' },
  { name: 'Hinayan, Jovan Earl P.' },
  { name: 'Labang, Jason William H.' },
  { name: 'Magallanes,Alyssa Danielle ' },
  { name: 'Mirasol, Mace Matthew L.' },
  { name: 'Narciso, Syra M.' },
  { name: 'Ortaliz, Tommy Renz B.' },
  { name: 'Palmaira, James Isaac L.' },
  { name: 'Pañer II, Luwen' },
  { name: 'Recabar, Bea Merr S.' },
  { name: 'Regalado, Madel E.' },
  { name: 'Reyes, Michael D.' },
  { name: 'Suazo, Roy II O.' },
  { name: 'Sucaldito, Agnes Grace S.' },
  { name: 'Medalla, Christian Homer' },
]

export { batch1, batch2, batch3, batch4 }
